### ISSUE TITLE
你要的JamellaD2E v3

### ISSUE THREAD

**Issue by tytannial** [zhaoleimxd/JamellaD2E#1]
![20211008193927](https://user-images.githubusercontent.com/11215623/136550562-b75c8e99-8546-4d92-9b31-c6285e82524b.png)

The Phrozen Keep上还保存有
[JamellaD2Editor_v3.zip](https://github.com/zhaoleimxd/JamellaD2E/files/7310918/JamellaD2Editor_v3.zip)

**Comment by zhaoleimxd** [comment]
卧槽，效率这么高，多谢大佬了~~~

**Comment by tytannial** [comment]
> 卧槽，效率这么高，多谢大佬了~~~

感觉以前用的最多的是shadowmaster 然而这东西源码的影子都找不到

**Comment by zhaoleimxd** [comment]
应该是没开源过，不过根据现有的文档和已经开源的项目已经大概能写出新的修改器来了。
